services:
  backend-bank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_bank
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-raspy-salad-alusqwli.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: ${NEON_USER}
      SPRING_DATASOURCE_PASSWORD: ${NEON_PASSWORD}
    ports:
      - "8080:8080"